// <auto-generated />
using System;
using Banking_system.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Banking_system.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20260618095934_NewFieldAdd")]
    partial class NewFieldAdd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Banking_system.Entity.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ipn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMale")
                        .HasColumnType("boolean");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Banking_system.Models.AbstractCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<short>("CVV")
                        .HasColumnType("smallint");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cards");

                    b.HasDiscriminator<string>("CardType").HasValue("AbstractCard");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Banking_system.Models.Transactions.AbstractTransaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("CardId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionTarget")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.HasKey("id");

                    b.HasIndex("CardId");

                    b.ToTable("transactions");

                    b.HasDiscriminator<string>("TransactionType").HasValue("AbstractTransaction");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Banking_system.Models.CreditCard", b =>
                {
                    b.HasBaseType("Banking_system.Models.AbstractCard");

                    b.Property<decimal>("AccruedInterest")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreditLimit")
                        .HasColumnType("integer");

                    b.Property<string>("CreditType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastReminderSentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MissedPaymentsCount")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Credit");
                });

            modelBuilder.Entity("Banking_system.Models.CurrencyCard", b =>
                {
                    b.HasBaseType("Banking_system.Models.AbstractCard");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Currency");
                });

            modelBuilder.Entity("Banking_system.Models.DebitCard", b =>
                {
                    b.HasBaseType("Banking_system.Models.AbstractCard");

                    b.HasDiscriminator().HasValue("Debit");
                });

            modelBuilder.Entity("Banking_system.Models.Transactions.CurrencyExchangeTransaction", b =>
                {
                    b.HasBaseType("Banking_system.Models.Transactions.AbstractTransaction");

                    b.HasDiscriminator().HasValue("Exchange");
                });

            modelBuilder.Entity("Banking_system.Models.Transactions.DepositTransaction", b =>
                {
                    b.HasBaseType("Banking_system.Models.Transactions.AbstractTransaction");

                    b.HasDiscriminator().HasValue("Deposit");
                });

            modelBuilder.Entity("Banking_system.Models.Transactions.TransferTransaction", b =>
                {
                    b.HasBaseType("Banking_system.Models.Transactions.AbstractTransaction");

                    b.HasDiscriminator().HasValue("Transfer");
                });

            modelBuilder.Entity("Banking_system.Models.Transactions.WithdrawTransaction", b =>
                {
                    b.HasBaseType("Banking_system.Models.Transactions.AbstractTransaction");

                    b.HasDiscriminator().HasValue("Withdraw");
                });

            modelBuilder.Entity("Banking_system.Models.AbstractCard", b =>
                {
                    b.HasOne("Banking_system.Entity.User", null)
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Banking_system.Models.Transactions.AbstractTransaction", b =>
                {
                    b.HasOne("Banking_system.Models.AbstractCard", null)
                        .WithMany("LastTransactions")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Banking_system.Entity.User", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Banking_system.Models.AbstractCard", b =>
                {
                    b.Navigation("LastTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
